### ISSUE TITLE
can not readFile that captured as tmpfile

### ISSUE THREAD

**Issue by personapp** [gre/react-native-view-shot#159]
readFile() method of both "react-native-fs" and "rn-fetch-blob" works well for static asset files or the output of "react-native-camera" library. But the readFile() method can not read the file that captured via "react-native-view-shot" as tmpfile.

react-native@0.52.2
react-native-view-shot@2.3.0
react-native-fetch-blob@0.10.8
rn-fetch-blob@0.10.11
react-native-fs@2.10.14

```
class SomeComponent extends Component {
  async captureAndReadFile() {
    try {
      let filePath = await this.viewShot.capture() ;
      let data = await RNFS.readFile(filePath, 'base64');  // or RNFetchBlob.fs.readFile(filePath, 'base64');
      return data && new Buffer.from(data, 'base64'); 
    }
    catch(err) {
      console.warn(err);
    }
  }

  render() {
    return(
      <View>
        <ViewShot 
          ref={ref => this.viewShot = ref}
          options={{ format: 'jpg', quality: 0.8 }}
        />
        <Button title="Press" onPress={this.captureAndReadFile.bind(this)}
      </View>
    );
  }
```

Am I missing something ?
Thanks in advance.

**Comment by gre** [comment]
how do you check if it worked? is console.warn logging something?

**Comment by personapp** [comment]
This is not the full code. I reduced it to highlight the issue.

console.warn logs that RNFetchBlob failed to reas file. This only happened when the filePath comes from react-native-view-shot

**Comment by personapp** [comment]
I also tried to read file via ImageStore. It throwed "ERCTERRORDOMAIN0" error.

**Comment by personapp** [comment]
Any solution please.

**Comment by jgreen210** [comment]
Android or ios or both?

**Comment by jgreen210** [comment]
If this problem you are having is just for android, there's some chance https://github.com/gre/react-native-view-shot/pull/169 might help.  Although, I suspect you have some other problem. That's since we didn't get any failures due to the issue fixed by this PR in our tests (which compare pngs saved by this library with checked-in reference images) and since you're getting errors for base64 images too, and there's no buffering involved in that case.

**Comment by serhiipalash** [comment]
Hi @gre ! 
I think this bug is still active.

`Expo.takeSnapthosAsync` has this bug in Expo 31 compare to Expo 30 (iOS tested). In Expo 31 `takeSnapthosAsync` was updated to use `react-native-view-shot` v2.5.0, and now `takeSnapthosAsync` result "tmpfile" uri is not compossible with `Expo.MediaLibrary` or `Expo.FileSystem` any more. That is because the uri path is in `/private/var/...` and `Expo.MediaLibrary` and `Expo.FileSystem` can only work with paths that are in public system scope `/var/...`. When you try to save taken view snapshot to user photos or temporary dir, you will see an error "Couldn't read ...".

As I remember in Expo 30 version of `react-native-view-shot` was something around v1.1.0.

**Comment by gre** [comment]
I think this is fixed. I was properly able to get the data from file and render it back in https://github.com/gre/react-native-view-shot/commit/8a6ea61c300d4ee7cb4fae2b9eec28d3c0b95dfe

works on iOS and Android.

Please report back if you are still having an issue (writing an example to reproduce the bug is the best)

**Comment by jagdeepChicmic** [comment]
still facing this issue in IOS


**Error processing request body: Error Domain=NSCocoaErrorDomain Code=260 "The file “623FB73D-2BB8-45D6-B0F7-70817C548123.png” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/private/var/mobile/Containers/Data/Application/A1FDA452-0CED-461B-BC08-799BA0CCB3DB/tmp/ReactNative/623FB73D-2BB8-45D6-B0F7-70817C548123.png, NSUnderlyingError=0x281aecb40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}**

**Comment by ColeTownsend** [comment]
@jagdeepChicmic also ran into that issue on Expo 48

**Comment by jagdeepChicmic** [comment]
@ColeTownsend but i'm trying this on CLI enviourment.

**Comment by Obrazcoff** [comment]
I have same issue on
    "expo": "~49.0.15",
    "expo-file-system": "~15.4.5",
    "react-native-view-shot": "3.7.0",
    
Library/Developer/CoreSimulator/Devices/54F0B65B-7D7F-4F0C-9867-9A8E0FF6AC04/data/Containers/Data/Appli ... 617F.png' isn't readable.]

**Comment by GitKat** [comment]
Try step by step.
1- First step is to see if the file exist
2- see if you can access the directory
3- console.log the dir data

also try using react-native-fs. it is pretty straight forward

i am using rn shots but not using expo
